#include "stm32f1xx_hal.h"
#include <stdio.h>
#include <stdint.h>
#include "../Inc/sensor_c.h"

/* Prototypes for functions generated by CubeMX in your project */
extern void SystemClock_Config(void);
extern void MX_GPIO_Init(void);
extern void MX_USART2_UART_Init(void);
extern UART_HandleTypeDef huart2;

/* bench_run is provided in sensor_bench.c */
extern void bench_run(uint32_t results[8]);

/* --- ASM/C benchmark helpers --- */
extern uint32_t test_fn_asm(uint32_t x); /* implemented in test_fn.s */

static uint32_t test_fn_c(uint32_t x){
    return x * 3u + 7u; /* simple C implementation to compare */
}

static inline void dwt_init(void){
    CoreDebug->DEMCR |= CoreDebug_DEMCR_TRCENA_Msk;
    DWT->CYCCNT = 0;
    DWT->CTRL |= DWT_CTRL_CYCCNTENA_Msk;
}
static inline uint32_t dwt_get(void){ return DWT->CYCCNT; }

typedef struct { uint32_t cycles; uint32_t result; } sample_t;
#define SAMPLES 32
static sample_t c_samples[SAMPLES];
static sample_t asm_samples[SAMPLES];

static void run_asm_c_bench(void){
    dwt_init();
    for(uint32_t i=0;i<SAMPLES;i++){
        uint32_t in = i + 1u;
        uint32_t s = dwt_get();
        uint32_t out = test_fn_c(in);
        uint32_t e = dwt_get();
        c_samples[i].cycles = e - s;
        c_samples[i].result = out;

        s = dwt_get();
        out = test_fn_asm(in);
        e = dwt_get();
        asm_samples[i].cycles = e - s;
        asm_samples[i].result = out;
    }

    /* Send CSV header */
    char hdr[] = "idx,c_cycles,c_result,asm_cycles,asm_result\r\n";
    HAL_UART_Transmit(&huart2, (uint8_t*)hdr, (uint16_t)sizeof(hdr)-1, HAL_MAX_DELAY);

    /* Send rows */
    char buf[80];
    for(uint32_t i=0;i<SAMPLES;i++){
        int n = snprintf(buf, sizeof(buf), "%lu,%lu,%lu,%lu,%lu\r\n",
            (unsigned long)i,
            (unsigned long)c_samples[i].cycles,
            (unsigned long)c_samples[i].result,
            (unsigned long)asm_samples[i].cycles,
            (unsigned long)asm_samples[i].result);
        if(n>0) HAL_UART_Transmit(&huart2, (uint8_t*)buf, (uint16_t)n, HAL_MAX_DELAY);
    }
}

int main(void)
{
    HAL_Init();

    /* Setup system clock and peripherals (implemented in your project) */
    SystemClock_Config();
    MX_GPIO_Init();
    MX_USART2_UART_Init();

    uint32_t results[8] = {0};

    /* Run benchmark (initialises DWT internally) */
    bench_run(results);

    /* Print results over USART2 */
    char buf[160];
    int n = snprintf(buf, sizeof(buf),
        "c_dwt=%lu asm_dwt=%lu c_delay=%lu asm_delay=%lu c_set=%lu asm_set=%lu\r\n",
        (unsigned long)results[0], (unsigned long)results[1],
        (unsigned long)results[2], (unsigned long)results[3],
        (unsigned long)results[4], (unsigned long)results[5]);

    if (n > 0) {
        HAL_UART_Transmit(&huart2, (uint8_t*)buf, (uint16_t)n, HAL_MAX_DELAY);
    }

    /* Run additional ASM vs C micro-benchmark and export CSV over UART */
    run_asm_c_bench();

    /* For ultrasonic/ADC: call c_ultrasonic_ticks/asm_ultrasonic_ticks and print similarly when hardware attached. */

    while (1) {
        HAL_Delay(1000);
    }
}
