/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file           : main.c
  * @brief          : Intelligent obstacle-avoiding car — STM32F103
  *
  * Sensor layout (bird's-eye):
  *   US3(L) ←  [BOT]  → US1(R)
  *   US4(FL)↗         ↖US2(FR)
  *              [FWD]
  *   US6(RL)↙         ↘US5(RR)
  *
  * Navigation logic:
  *   • Default: drive FORWARD, speed ∝ front clearance
  *   • Front blocked → PIVOT away from obstruction
  *   • Pivot timeout → BACKWARD
  *   • Reversing → check US5/US6, stop if rear hit
  *   • IR object → full STOP, blare buzzer
  *   • Side walls → gentle steering before hard turn
  *
  * LED / Buzzer:
  *   • FWD clear  : slow heartbeat (1 Hz)
  *   • FWD warn   : faster blink, proximity-proportional buzzer
  *   • PIVOT LEFT : LED1 rapid blink (5 Hz turn signal)
  *   • PIVOT RIGHT: LED2 rapid blink (5 Hz turn signal)
  *   • BACKWARD   : LEDs alternate + buzzer chirp (reversing beep)
  *   • STOP/IR    : both LEDs solid + buzzer solid
  *
  * Servo: continuous left↔right sweep (no lock-out).
  ******************************************************************************
  */
/* USER CODE END Header */

#include "main.h"
#include <stdio.h>
#include <string.h>

/* =====================================================================
   DEFINES
   ===================================================================== */
#define ADC_TIMEOUT_MS        10U
#define US_MIN_CM             2.0f
#define US_MAX_CM           300.0f
#define US_GAP_MS             25U      /* inter-sensor crosstalk guard */
#define IR_ALERT_TH         1000U      /* ADC counts below this = object */

/* Servo (TIM1_CH4) --------------------------------------------------- */
#define SERVO_LEFT_US        1000U
#define SERVO_CENTER_US      1500U
#define SERVO_RIGHT_US       2000U
#define SERVO_HALF_SWEEP_MS  2500U    /* left→right in 2.5 s, same back */

/* Motor 1 (left wheel): ENA→PA6(TIM3_CH1 PWM speed),
                          IN1→PB14, IN2→PB15 (direction GPIOs)
   Motor 2 (right wheel): ENB→PB13 (GPIO on/off, no PWM),
                           IN3→PC7,  IN4→PC8 (direction GPIOs)       */
#define M1_ENA_PORT          GPIOA
#define M1_ENA_PIN           GPIO_PIN_6    /* TIM3_CH1 AF drives speed */
#define M1_IN1_PORT          GPIOB
#define M1_IN1_PIN           GPIO_PIN_14
#define M1_IN2_PORT          GPIOB
#define M1_IN2_PIN           GPIO_PIN_15
#define M1_PWM_PERIOD        999U

#define M2_ENB_PORT          GPIOB
#define M2_ENB_PIN           GPIO_PIN_13
#define M2_IN3_PORT          GPIOC
#define M2_IN3_PIN           GPIO_PIN_7
#define M2_IN4_PORT          GPIOC
#define M2_IN4_PIN           GPIO_PIN_8

/* Forward polarity — swap if wheels spin wrong way */
#define M1_FWD_IN1           GPIO_PIN_SET
#define M1_FWD_IN2           GPIO_PIN_RESET
#define M2_FWD_IN3           GPIO_PIN_RESET
#define M2_FWD_IN4           GPIO_PIN_SET

/* Motor duty (0 – M1_PWM_PERIOD = 0 – 999) */
#define DUTY_FULL            900U
#define DUTY_SLOW            350U

/* Navigation thresholds (cm) */
#define NAV_CRITICAL_CM       6.0f    /* Emergency brake */
#define NAV_FRONT_STOP_CM    25.0f    /* Trigger turn decision */
#define NAV_FRONT_WARN_CM    40.0f    /* Start slowing */
#define NAV_SIDE_WARN_CM     15.0f    /* Steer away from wall */
#define NAV_REAR_STOP_CM     18.0f    /* Stop reversing */

/* Navigation timing (ms) */
#define PIVOT_MIN_MS         600U     /* Minimum pivot before checking clear */
#define PIVOT_MAX_MS        1800U     /* Give up pivoting → go backward */
#define BACKUP_MS            900U     /* Reverse duration */
#define STOP_ASSESS_MS       350U     /* Pause before reassessing */

/* Ultrasonic pins */
#define US1_TRIG_PORT  GPIOC
#define US1_TRIG_PIN   GPIO_PIN_0
#define US1_ECHO_PORT  GPIOA
#define US1_ECHO_PIN   GPIO_PIN_4

#define US2_TRIG_PORT  GPIOC
#define US2_TRIG_PIN   GPIO_PIN_1
#define US2_ECHO_PORT  GPIOC
#define US2_ECHO_PIN   GPIO_PIN_2

#define US3_TRIG_PORT  GPIOC
#define US3_TRIG_PIN   GPIO_PIN_3
#define US3_ECHO_PORT  GPIOC
#define US3_ECHO_PIN   GPIO_PIN_6

#define US4_TRIG_PORT  GPIOC
#define US4_TRIG_PIN   GPIO_PIN_5
#define US4_ECHO_PORT  GPIOA
#define US4_ECHO_PIN   GPIO_PIN_5

#define US5_TRIG_PORT  GPIOB
#define US5_TRIG_PIN   GPIO_PIN_0
#define US5_ECHO_PORT  GPIOB
#define US5_ECHO_PIN   GPIO_PIN_1

#define US6_TRIG_PORT  GPIOB
#define US6_TRIG_PIN   GPIO_PIN_10
#define US6_ECHO_PORT  GPIOB
#define US6_ECHO_PIN   GPIO_PIN_11

/* Output pins */
#define BUZZER_PORT      GPIOB
#define BUZZER_PIN       GPIO_PIN_8
#define ALERT_LED_PORT   GPIOB    /* LED1 – rear-right side indicator */
#define ALERT_LED_PIN    GPIO_PIN_9
#define ALERT_LED2_PORT  GPIOB    /* LED2 – rear-left  side indicator */
#define ALERT_LED2_PIN   GPIO_PIN_12

/* =====================================================================
   PERIPHERAL HANDLES (generated by CubeMX)
   ===================================================================== */
ADC_HandleTypeDef   hadc1;
I2C_HandleTypeDef   hi2c1;
TIM_HandleTypeDef   htim1;
TIM_HandleTypeDef   htim3;
UART_HandleTypeDef  huart2;

/* =====================================================================
   NAVIGATION STATE
   ===================================================================== */
typedef enum {
    NAV_FORWARD     = 0,
    NAV_PIVOT_LEFT,     /* spin CCW: M1 back, M2 fwd */
    NAV_PIVOT_RIGHT,    /* spin CW : M1 fwd, M2 back */
    NAV_BACKWARD,
    NAV_STOP,
} NavState_t;

static NavState_t g_nav        = NAV_STOP;
static uint32_t   g_nav_start  = 0U;

/* Latest rear readings — updated during main loop, used by gap delay */
static volatile float    g_us5  = -1.0f;
static volatile float    g_us6  = -1.0f;
static volatile uint16_t g_ir   = 0xFFFFU;

/* =====================================================================
   PRIVATE FUNCTION PROTOTYPES
   ===================================================================== */
void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_ADC1_Init(void);
static void MX_TIM1_Init(void);
static void MX_TIM3_Init(void);
static void MX_I2C1_Init(void);
static void MX_USART2_UART_Init(void);

/* =====================================================================
   PRINTF RETARGET → USART2
   ===================================================================== */
int _write(int file, char *ptr, int len)
{
    (void)file;
    (void)HAL_UART_Transmit(&huart2, (uint8_t *)ptr, (uint16_t)len, 100U);
    return len;
}

/* =====================================================================
   DWT MICROSECOND DELAY
   ===================================================================== */
static void DWT_Init(void)
{
    CoreDebug->DEMCR |= CoreDebug_DEMCR_TRCENA_Msk;
    DWT->CTRL        |= DWT_CTRL_CYCCNTENA_Msk;
}

static void delay_us(uint32_t us)
{
    uint32_t start = DWT->CYCCNT;
    uint32_t ticks = us * (SystemCoreClock / 1000000U);
    while ((DWT->CYCCNT - start) < ticks);
}

/* =====================================================================
   ULTRASONIC READ  (returns cm, −1 on timeout / out of range)
   ===================================================================== */
static float ultrasonic_read(GPIO_TypeDef *tp, uint16_t t_pin,
                              GPIO_TypeDef *ep, uint16_t e_pin)
{
    uint32_t to = 30000U;
    HAL_GPIO_WritePin(tp, t_pin, GPIO_PIN_RESET); delay_us(2U);
    HAL_GPIO_WritePin(tp, t_pin, GPIO_PIN_SET);   delay_us(10U);
    HAL_GPIO_WritePin(tp, t_pin, GPIO_PIN_RESET);

    while (HAL_GPIO_ReadPin(ep, e_pin) == GPIO_PIN_RESET)
        if (--to == 0U) return -1.0f;

    uint32_t t0 = DWT->CYCCNT;

    while (HAL_GPIO_ReadPin(ep, e_pin) == GPIO_PIN_SET)
        if (--to == 0U) return -1.0f;

    float dt_us = (float)(DWT->CYCCNT - t0) / (float)(SystemCoreClock / 1000000U);
    float cm    = (dt_us * 0.0343f) / 2.0f;
    return ((cm < US_MIN_CM) || (cm > US_MAX_CM)) ? -1.0f : cm;
}

/* =====================================================================
   IR READ  (12-bit ADC)
   ===================================================================== */
static uint16_t read_ir(void)
{
    if (HAL_ADC_Start(&hadc1) != HAL_OK) return 0xFFFFU;
    if (HAL_ADC_PollForConversion(&hadc1, ADC_TIMEOUT_MS) != HAL_OK) return 0xFFFFU;
    return (uint16_t)HAL_ADC_GetValue(&hadc1);
}

/* =====================================================================
   HELPER: treat invalid (−1) as "very far" for navigation decisions
   ===================================================================== */
static float nav_cm(float raw) { return (raw < US_MIN_CM) ? 999.0f : raw; }

/* =====================================================================
   SERVO — CONTINUOUS PING-PONG SWEEP (no lock-out)
   ===================================================================== */
static void servo_config_50hz(void)
{
    RCC_ClkInitTypeDef clk = {0};
    uint32_t fl = 0U;
    HAL_RCC_GetClockConfig(&clk, &fl);
    uint32_t pclk2   = HAL_RCC_GetPCLK2Freq();
    uint32_t ppre2   = (clk.APB2CLKDivider == RCC_HCLK_DIV1) ? 1U : 2U;
    uint32_t tim_clk = (ppre2 == 1U) ? pclk2 : (pclk2 * 2U);
    if (tim_clk < 1000000U) return;
    __HAL_TIM_SET_PRESCALER(&htim1, (tim_clk / 1000000U) - 1U);
    __HAL_TIM_SET_AUTORELOAD(&htim1, 20000U - 1U);
    __HAL_TIM_SET_COUNTER(&htim1, 0U);
    (void)HAL_TIM_GenerateEvent(&htim1, TIM_EVENTSOURCE_UPDATE);
}

static void servo_set_us(uint16_t us)
{
    if (us < SERVO_LEFT_US)  us = SERVO_LEFT_US;
    if (us > SERVO_RIGHT_US) us = SERVO_RIGHT_US;
    __HAL_TIM_SET_COMPARE(&htim1, TIM_CHANNEL_4, us);
}

/* Call each loop tick — smooth sweep based on HAL_GetTick() modulo */
static void servo_sweep_update(void)
{
    uint32_t period = (uint32_t)SERVO_HALF_SWEEP_MS * 2U;
    uint32_t phase  = HAL_GetTick() % period;
    uint16_t us;
    if (phase < (uint32_t)SERVO_HALF_SWEEP_MS) {
        float t = (float)phase / (float)SERVO_HALF_SWEEP_MS;
        us = (uint16_t)((float)SERVO_LEFT_US + t * (float)(SERVO_RIGHT_US - SERVO_LEFT_US));
    } else {
        float t = (float)(phase - (uint32_t)SERVO_HALF_SWEEP_MS) / (float)SERVO_HALF_SWEEP_MS;
        us = (uint16_t)((float)SERVO_RIGHT_US - t * (float)(SERVO_RIGHT_US - SERVO_LEFT_US));
    }
    servo_set_us(us);
}

/* =====================================================================
   MOTOR PRIMITIVES
   ===================================================================== */
static void m1_set_pwm(uint32_t duty)
{
    if (duty > M1_PWM_PERIOD) duty = M1_PWM_PERIOD;
    __HAL_TIM_SET_COMPARE(&htim3, TIM_CHANNEL_1, duty);
    __HAL_TIM_SET_COMPARE(&htim3, TIM_CHANNEL_2, 0U);
}

static void m1_forward(uint32_t duty)
{
    HAL_GPIO_WritePin(M1_ENA_PORT, M1_ENA_PIN, GPIO_PIN_SET);
    HAL_GPIO_WritePin(M1_IN1_PORT, M1_IN1_PIN, M1_FWD_IN1);
    HAL_GPIO_WritePin(M1_IN2_PORT, M1_IN2_PIN, M1_FWD_IN2);
    m1_set_pwm(duty);
}

static void m1_backward(uint32_t duty)
{
    HAL_GPIO_WritePin(M1_ENA_PORT, M1_ENA_PIN, GPIO_PIN_SET);
    /* Invert forward polarity */
    HAL_GPIO_WritePin(M1_IN1_PORT, M1_IN1_PIN, (M1_FWD_IN1 == GPIO_PIN_SET) ? GPIO_PIN_RESET : GPIO_PIN_SET);
    HAL_GPIO_WritePin(M1_IN2_PORT, M1_IN2_PIN, (M1_FWD_IN2 == GPIO_PIN_SET) ? GPIO_PIN_RESET : GPIO_PIN_SET);
    m1_set_pwm(duty);
}

static void m1_stop(void)
{
    m1_set_pwm(0U);
    HAL_GPIO_WritePin(M1_ENA_PORT, M1_ENA_PIN, GPIO_PIN_RESET);
}

static void m2_forward(void)
{
    HAL_GPIO_WritePin(M2_ENB_PORT, M2_ENB_PIN, GPIO_PIN_SET);
    HAL_GPIO_WritePin(M2_IN3_PORT, M2_IN3_PIN, M2_FWD_IN3);
    HAL_GPIO_WritePin(M2_IN4_PORT, M2_IN4_PIN, M2_FWD_IN4);
}

static void m2_backward(void)
{
    HAL_GPIO_WritePin(M2_ENB_PORT, M2_ENB_PIN, GPIO_PIN_SET);
    HAL_GPIO_WritePin(M2_IN3_PORT, M2_IN3_PIN, (M2_FWD_IN3 == GPIO_PIN_SET) ? GPIO_PIN_RESET : GPIO_PIN_SET);
    HAL_GPIO_WritePin(M2_IN4_PORT, M2_IN4_PIN, (M2_FWD_IN4 == GPIO_PIN_SET) ? GPIO_PIN_RESET : GPIO_PIN_SET);
}

static void m2_stop(void)
{
    HAL_GPIO_WritePin(M2_ENB_PORT, M2_ENB_PIN, GPIO_PIN_RESET);
}

/* ---- Composite motor commands ---- */
static void motors_stop(void)         { m1_stop();             m2_stop();     }
static void motors_forward(uint32_t d){ m1_forward(d);         m2_forward();  }
static void motors_backward(uint32_t d){m1_backward(d);        m2_backward(); }
static void motors_pivot_left(void)   { m1_backward(DUTY_FULL); m2_forward(); }
static void motors_pivot_right(void)  { m1_forward(DUTY_FULL);  m2_backward();}
/* Gentle steer: one side slows, other full speed */
static void motors_steer_left(void)   { m1_forward(DUTY_SLOW);  m2_forward(); }
static void motors_steer_right(void)  { m1_forward(DUTY_FULL);  m2_stop();    }

/* =====================================================================
   LED / BUZZER — state-aware, non-blocking
   ===================================================================== */
static void alert_update(NavState_t state, float us5_cm, float us6_cm, uint16_t ir_raw)
{
    static uint32_t     last_tog   = 0U;
    static GPIO_PinState led1      = GPIO_PIN_RESET;
    static GPIO_PinState led2      = GPIO_PIN_RESET;
    static GPIO_PinState buz       = GPIO_PIN_RESET;

    uint32_t now    = HAL_GetTick();
    uint8_t  ir_on  = (ir_raw != 0xFFFFU) && (ir_raw < IR_ALERT_TH);
    float    s5     = nav_cm(us5_cm);
    float    s6     = nav_cm(us6_cm);
    float    rear   = (s5 < s6) ? s5 : s6;

    /* ---- PRIORITY 1: IR object or critical rear → solid on ---- */
    if (ir_on || (rear < NAV_CRITICAL_CM)) {
        led1 = led2 = buz = GPIO_PIN_SET;
        HAL_GPIO_WritePin(BUZZER_PORT,     BUZZER_PIN,     buz);
        HAL_GPIO_WritePin(ALERT_LED_PORT,  ALERT_LED_PIN,  led1);
        HAL_GPIO_WritePin(ALERT_LED2_PORT, ALERT_LED2_PIN, led2);
        return;
    }

    uint32_t half_ms = 0U;   /* toggle half-period; 0 = no toggle this state */

    switch (state) {

    case NAV_FORWARD:
        /* Rear proximity buzzer — louder/faster as object approaches */
        if (rear < NAV_REAR_STOP_CM) {
            float ratio = 1.0f - ((rear - NAV_CRITICAL_CM) /
                                  (NAV_REAR_STOP_CM - NAV_CRITICAL_CM));
            if (ratio < 0.0f) ratio = 0.0f;
            if (ratio > 1.0f) ratio = 1.0f;
            half_ms = (uint32_t)(350U - ratio * 270.0f);   /* 80 – 350 ms */
            /* Buzzer follows blink; LEDs show which rear sensor */
            if ((now - last_tog) >= half_ms) {
                led1 = (s5 < NAV_REAR_STOP_CM) ?
                       ((led1 == GPIO_PIN_SET) ? GPIO_PIN_RESET : GPIO_PIN_SET) : GPIO_PIN_RESET;
                led2 = (s6 < NAV_REAR_STOP_CM) ?
                       ((led2 == GPIO_PIN_SET) ? GPIO_PIN_RESET : GPIO_PIN_SET) : GPIO_PIN_RESET;
                buz  = (led1 == GPIO_PIN_SET) || (led2 == GPIO_PIN_SET) ?
                       GPIO_PIN_SET : GPIO_PIN_RESET;
                last_tog = now;
            }
        } else {
            /* Slow heartbeat: both LEDs gentle pulse, buzzer off */
            half_ms = 500U;
            if ((now - last_tog) >= half_ms) {
                led1 = led2 = (led1 == GPIO_PIN_SET) ? GPIO_PIN_RESET : GPIO_PIN_SET;
                buz         = GPIO_PIN_RESET;
                last_tog    = now;
            }
        }
        break;

    case NAV_PIVOT_LEFT:
        /* Left turn indicator: LED1 rapid blink (≈5 Hz) */
        if ((now - last_tog) >= 100U) {
            led1 = (led1 == GPIO_PIN_SET) ? GPIO_PIN_RESET : GPIO_PIN_SET;
            led2 = GPIO_PIN_RESET;
            buz  = GPIO_PIN_RESET;
            last_tog = now;
        }
        break;

    case NAV_PIVOT_RIGHT:
        /* Right turn indicator: LED2 rapid blink (≈5 Hz) */
        if ((now - last_tog) >= 100U) {
            led2 = (led2 == GPIO_PIN_SET) ? GPIO_PIN_RESET : GPIO_PIN_SET;
            led1 = GPIO_PIN_RESET;
            buz  = GPIO_PIN_RESET;
            last_tog = now;
        }
        break;

    case NAV_BACKWARD:
        /* Reverse: LEDs alternate fast + buzzer chirps like a truck */
        if ((now - last_tog) >= 130U) {
            led1     = (led1 == GPIO_PIN_SET) ? GPIO_PIN_RESET : GPIO_PIN_SET;
            led2     = (led1 == GPIO_PIN_SET) ? GPIO_PIN_RESET : GPIO_PIN_SET;  /* opposite */
            buz      = led1;   /* buzzer pulses with LED1 */
            last_tog = now;
        }
        break;

    case NAV_STOP:
    default:
        /* Assessment pause: both LEDs medium blink, buzzer off */
        if ((now - last_tog) >= 200U) {
            led1 = led2 = (led1 == GPIO_PIN_SET) ? GPIO_PIN_RESET : GPIO_PIN_SET;
            buz         = GPIO_PIN_RESET;
            last_tog    = now;
        }
        break;
    }

    HAL_GPIO_WritePin(BUZZER_PORT,     BUZZER_PIN,     buz);
    HAL_GPIO_WritePin(ALERT_LED_PORT,  ALERT_LED_PIN,  led1);
    HAL_GPIO_WritePin(ALERT_LED2_PORT, ALERT_LED2_PIN, led2);
}

/* =====================================================================
   NAVIGATION STATE MACHINE
   ===================================================================== */
static void nav_set(NavState_t s)
{
    g_nav       = s;
    g_nav_start = HAL_GetTick();
}

static uint32_t nav_elapsed(void) { return HAL_GetTick() - g_nav_start; }

static void nav_update(float us1, float us2, float us3, float us4,
                       float us5, float us6, uint8_t ir)
{
    /* Convert to safe values: −1 (invalid/no echo) → 999 (treat as clear) */
    float s1 = nav_cm(us1);   /* right       */
    float s2 = nav_cm(us2);   /* front-right */
    float s3 = nav_cm(us3);   /* left        */
    float s4 = nav_cm(us4);   /* front-left  */
    float s5 = nav_cm(us5);   /* rear-right  */
    float s6 = nav_cm(us6);   /* rear-left   */

    /* Pre-compute condition flags */
    uint8_t front_r_block = (s2 < NAV_FRONT_STOP_CM);
    uint8_t front_l_block = (s4 < NAV_FRONT_STOP_CM);
    uint8_t front_block   = front_r_block || front_l_block;
    uint8_t front_crit    = (s2 < NAV_CRITICAL_CM) || (s4 < NAV_CRITICAL_CM);
    uint8_t rear_block    = (s5 < NAV_REAR_STOP_CM) || (s6 < NAV_REAR_STOP_CM);
    uint8_t right_wall    = (s1 < NAV_SIDE_WARN_CM);
    uint8_t left_wall     = (s3 < NAV_SIDE_WARN_CM);

    /* ---- IR object: hard stop, priority over everything ---- */
    if (ir && (g_nav != NAV_STOP)) {
        motors_stop();
        nav_set(NAV_STOP);
        return;
    }

    switch (g_nav) {

    /* ================================================================
       FORWARD
       ================================================================ */
    case NAV_FORWARD:

        /* Emergency brake */
        if (front_crit) {
            motors_stop();
            nav_set(NAV_STOP);
            break;
        }

        /* Need to turn */
        if (front_block) {
            motors_stop();
            /*
             * Choose spin direction:
             *  - Front-right closer → obstacle on right → pivot LEFT
             *  - Front-left  closer → obstacle on left  → pivot RIGHT
             *  - If sides also blocked, pick side with more space
             */
            if (front_r_block && !front_l_block) {
                nav_set(NAV_PIVOT_LEFT);
            } else if (front_l_block && !front_r_block) {
                nav_set(NAV_PIVOT_RIGHT);
            } else {
                /* Both front blocked — use side sensors to decide */
                nav_set((s1 > s3) ? NAV_PIVOT_RIGHT : NAV_PIVOT_LEFT);
            }
            break;
        }

        /* Gentle wall-following steer (side sensors) */
        if (right_wall && !left_wall) {
            motors_steer_left();    /* right wall → drift left */
        } else if (left_wall && !right_wall) {
            motors_steer_right();   /* left wall  → drift right */
        } else {
            /* Open road — speed proportional to nearest front distance */
            float front_min = (s2 < s4) ? s2 : s4;
            uint32_t duty   = DUTY_FULL;
            if (front_min < NAV_FRONT_WARN_CM) {
                float ratio = (front_min - NAV_FRONT_STOP_CM) /
                              (NAV_FRONT_WARN_CM - NAV_FRONT_STOP_CM);
                if (ratio < 0.0f) ratio = 0.0f;
                if (ratio > 1.0f) ratio = 1.0f;
                duty = (uint32_t)(DUTY_SLOW + ratio * (float)(DUTY_FULL - DUTY_SLOW));
            }
            motors_forward(duty);
        }
        break;

    /* ================================================================
       PIVOT LEFT
       ================================================================ */
    case NAV_PIVOT_LEFT:
        motors_pivot_left();

        if (nav_elapsed() >= PIVOT_MAX_MS) {
            /* Spinning too long, go back instead */
            nav_set(NAV_BACKWARD);
            break;
        }
        /* Once front clear (and minimum time elapsed) → go forward */
        if (!front_block && (nav_elapsed() >= PIVOT_MIN_MS)) {
            nav_set(NAV_FORWARD);
        }
        break;

    /* ================================================================
       PIVOT RIGHT
       ================================================================ */
    case NAV_PIVOT_RIGHT:
        motors_pivot_right();

        if (nav_elapsed() >= PIVOT_MAX_MS) {
            nav_set(NAV_BACKWARD);
            break;
        }
        if (!front_block && (nav_elapsed() >= PIVOT_MIN_MS)) {
            nav_set(NAV_FORWARD);
        }
        break;

    /* ================================================================
       BACKWARD
       ================================================================ */
    case NAV_BACKWARD:
        /* Rear sensors: instant stop if something behind */
        if (rear_block) {
            motors_stop();
            /*
             * Rear blocked — choose spin away from the blocked rear sensor
             * US5 = rear-right, US6 = rear-left
             */
            nav_set((s5 < s6) ? NAV_PIVOT_LEFT : NAV_PIVOT_RIGHT);
            break;
        }

        motors_backward(DUTY_SLOW);

        if (nav_elapsed() >= BACKUP_MS) {
            /* Done reversing — choose spin based on side space */
            nav_set((s1 > s3) ? NAV_PIVOT_RIGHT : NAV_PIVOT_LEFT);
        }
        break;

    /* ================================================================
       STOP (assessment / IR triggered)
       ================================================================ */
    case NAV_STOP:
    default:
        motors_stop();

        if (nav_elapsed() >= STOP_ASSESS_MS) {
            if (!ir) {
                /* IR cleared — choose best move */
                if (!front_block) {
                    nav_set(NAV_FORWARD);
                } else {
                    nav_set((s1 > s3) ? NAV_PIVOT_RIGHT : NAV_PIVOT_LEFT);
                }
            }
            /* else stay stopped while IR sees object */
        }
        break;
    }
}

/* =====================================================================
   GAP DELAY — maintain alerts + servo during inter-sensor gaps
   ===================================================================== */
static void gap_delay(uint32_t ms)
{
    uint32_t end = HAL_GetTick() + ms;
    while (HAL_GetTick() < end) {
        alert_update(g_nav, g_us5, g_us6, g_ir);
        servo_sweep_update();
        HAL_Delay(5U);
    }
}

/* =====================================================================
   MAIN
   ===================================================================== */
int main(void)
{
    HAL_Init();
    SystemClock_Config();

    MX_GPIO_Init();
    MX_ADC1_Init();
    MX_I2C1_Init();
    MX_TIM1_Init();
    MX_TIM3_Init();
    MX_USART2_UART_Init();

    DWT_Init();
    DWT->CYCCNT = 0U;

    /* Servo setup */
    servo_config_50hz();
    (void)HAL_TIM_PWM_Start(&htim1, TIM_CHANNEL_4);
    servo_set_us(SERVO_CENTER_US);

    /* Motor PWM timers */
    (void)HAL_TIM_PWM_Start(&htim3, TIM_CHANNEL_1);
    (void)HAL_TIM_PWM_Start(&htim3, TIM_CHANNEL_2);

    /* Start stopped — let bot assess surroundings first */
    motors_stop();
    nav_set(NAV_STOP);

    printf("BOOT: obstacle-avoiding car\r\n");

    while (1)
    {
        /* ---------- Read IR ---------- */
        g_ir = read_ir();

        /* ---------- Read all 6 ultrasonic sensors (gaps service alerts) ---------- */
        float us1 = ultrasonic_read(US1_TRIG_PORT, US1_TRIG_PIN, US1_ECHO_PORT, US1_ECHO_PIN);
        gap_delay(US_GAP_MS);

        float us2 = ultrasonic_read(US2_TRIG_PORT, US2_TRIG_PIN, US2_ECHO_PORT, US2_ECHO_PIN);
        gap_delay(US_GAP_MS);

        float us3 = ultrasonic_read(US3_TRIG_PORT, US3_TRIG_PIN, US3_ECHO_PORT, US3_ECHO_PIN);
        gap_delay(US_GAP_MS);

        float us4 = ultrasonic_read(US4_TRIG_PORT, US4_TRIG_PIN, US4_ECHO_PORT, US4_ECHO_PIN);
        gap_delay(US_GAP_MS);

        float us5 = ultrasonic_read(US5_TRIG_PORT, US5_TRIG_PIN, US5_ECHO_PORT, US5_ECHO_PIN);
        gap_delay(US_GAP_MS);

        float us6 = ultrasonic_read(US6_TRIG_PORT, US6_TRIG_PIN, US6_ECHO_PORT, US6_ECHO_PIN);
        gap_delay(US_GAP_MS);

        /* Update globals for gap_delay usage in next iteration */
        g_us5 = us5;
        g_us6 = us6;

        /* ---------- Navigation ---------- */
        uint8_t ir_flag = (uint8_t)((g_ir != 0xFFFFU) && (g_ir < IR_ALERT_TH));
        nav_update(us1, us2, us3, us4, us5, us6, ir_flag);

        /* ---------- Alerts ---------- */
        alert_update(g_nav, us5, us6, g_ir);

        /* ---------- Servo ---------- */
        servo_sweep_update();

        /* ---------- Debug UART (every 500 ms) ---------- */
        {
            static uint32_t last_p = 0U;
            uint32_t now = HAL_GetTick();
            if ((now - last_p) >= 500U) {
                static const char *st[] = {"FWD","PIL","PIR","BCK","STP"};
                /* Use integer arithmetic to avoid %f linker dependency */
                int i1 = (us1 < 0.0f) ? -1 : (int)(us1 * 10.0f);
                int i2 = (us2 < 0.0f) ? -1 : (int)(us2 * 10.0f);
                int i3 = (us3 < 0.0f) ? -1 : (int)(us3 * 10.0f);
                int i4 = (us4 < 0.0f) ? -1 : (int)(us4 * 10.0f);
                int i5 = (us5 < 0.0f) ? -1 : (int)(us5 * 10.0f);
                int i6 = (us6 < 0.0f) ? -1 : (int)(us6 * 10.0f);
                printf("ST=%s IR=%u "
                       "U1=%d.%d U2=%d.%d U3=%d.%d "
                       "U4=%d.%d U5=%d.%d U6=%d.%d\r\n",
                       st[g_nav], (unsigned int)g_ir,
                       i1/10, (i1<0)?0:(i1%10),
                       i2/10, (i2<0)?0:(i2%10),
                       i3/10, (i3<0)?0:(i3%10),
                       i4/10, (i4<0)?0:(i4%10),
                       i5/10, (i5<0)?0:(i5%10),
                       i6/10, (i6<0)?0:(i6%10));
                last_p = now;
            }
        }
    }
}

/* =====================================================================
   SYSTEM CLOCK CONFIG  (8 MHz HSI ÷2 → PLL ×2 = 8 MHz SYSCLK)
   ===================================================================== */
void SystemClock_Config(void)
{
    RCC_OscInitTypeDef       osc  = {0};
    RCC_ClkInitTypeDef       clk  = {0};
    RCC_PeriphCLKInitTypeDef pclk = {0};

    osc.OscillatorType      = RCC_OSCILLATORTYPE_HSI;
    osc.HSIState            = RCC_HSI_ON;
    osc.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
    osc.PLL.PLLState        = RCC_PLL_ON;
    osc.PLL.PLLSource       = RCC_PLLSOURCE_HSI_DIV2;
    osc.PLL.PLLMUL          = RCC_PLL_MUL2;
    if (HAL_RCC_OscConfig(&osc) != HAL_OK) Error_Handler();

    clk.ClockType      = RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_SYSCLK |
                         RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2;
    clk.SYSCLKSource   = RCC_SYSCLKSOURCE_PLLCLK;
    clk.AHBCLKDivider  = RCC_SYSCLK_DIV1;
    clk.APB1CLKDivider = RCC_HCLK_DIV2;
    clk.APB2CLKDivider = RCC_HCLK_DIV1;
    if (HAL_RCC_ClockConfig(&clk, FLASH_LATENCY_0) != HAL_OK) Error_Handler();

    pclk.PeriphClockSelection = RCC_PERIPHCLK_ADC;
    pclk.AdcClockSelection    = RCC_ADCPCLK2_DIV2;
    if (HAL_RCCEx_PeriphCLKConfig(&pclk) != HAL_OK) Error_Handler();
}

/* =====================================================================
   ADC1 — channel 14 (PC4), IR sensor
   ===================================================================== */
static void MX_ADC1_Init(void)
{
    ADC_ChannelConfTypeDef sc = {0};

    hadc1.Instance                   = ADC1;
    hadc1.Init.ScanConvMode          = ADC_SCAN_DISABLE;
    hadc1.Init.ContinuousConvMode    = DISABLE;
    hadc1.Init.DiscontinuousConvMode = DISABLE;
    hadc1.Init.ExternalTrigConv      = ADC_SOFTWARE_START;
    hadc1.Init.DataAlign             = ADC_DATAALIGN_RIGHT;
    hadc1.Init.NbrOfConversion       = 1;
    if (HAL_ADC_Init(&hadc1) != HAL_OK) Error_Handler();

    sc.Channel      = ADC_CHANNEL_14;
    sc.Rank         = ADC_REGULAR_RANK_1;
    sc.SamplingTime = ADC_SAMPLETIME_1CYCLE_5;
    if (HAL_ADC_ConfigChannel(&hadc1, &sc) != HAL_OK) Error_Handler();
}

/* =====================================================================
   I2C1 — 100 kHz (for IMU, unused in this build)
   ===================================================================== */
static void MX_I2C1_Init(void)
{
    hi2c1.Instance             = I2C1;
    hi2c1.Init.ClockSpeed      = 100000;
    hi2c1.Init.DutyCycle       = I2C_DUTYCYCLE_2;
    hi2c1.Init.OwnAddress1     = 0;
    hi2c1.Init.AddressingMode  = I2C_ADDRESSINGMODE_7BIT;
    hi2c1.Init.DualAddressMode = I2C_DUALADDRESS_DISABLE;
    hi2c1.Init.OwnAddress2     = 0;
    hi2c1.Init.GeneralCallMode = I2C_GENERALCALL_DISABLE;
    hi2c1.Init.NoStretchMode   = I2C_NOSTRETCH_DISABLE;
    if (HAL_I2C_Init(&hi2c1) != HAL_OK) Error_Handler();
}

/* =====================================================================
   TIM1 — PWM for servo (CH4)
   Prescaler set at runtime by servo_config_50hz() to get 1 µs/tick
   ===================================================================== */
static void MX_TIM1_Init(void)
{
    TIM_ClockConfigTypeDef      scc  = {0};
    TIM_MasterConfigTypeDef     mc   = {0};
    TIM_OC_InitTypeDef          oc   = {0};
    TIM_BreakDeadTimeConfigTypeDef bd = {0};

    htim1.Instance               = TIM1;
    htim1.Init.Prescaler         = 63;        /* overwritten by servo_config_50hz */
    htim1.Init.CounterMode       = TIM_COUNTERMODE_UP;
    htim1.Init.Period            = 19999;     /* 20 ms at 1 MHz tick */
    htim1.Init.ClockDivision     = TIM_CLOCKDIVISION_DIV1;
    htim1.Init.RepetitionCounter = 0;
    htim1.Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_DISABLE;
    if (HAL_TIM_Base_Init(&htim1) != HAL_OK) Error_Handler();

    scc.ClockSource = TIM_CLOCKSOURCE_INTERNAL;
    if (HAL_TIM_ConfigClockSource(&htim1, &scc) != HAL_OK) Error_Handler();
    if (HAL_TIM_PWM_Init(&htim1) != HAL_OK) Error_Handler();

    mc.MasterOutputTrigger = TIM_TRGO_RESET;
    mc.MasterSlaveMode     = TIM_MASTERSLAVEMODE_DISABLE;
    if (HAL_TIMEx_MasterConfigSynchronization(&htim1, &mc) != HAL_OK) Error_Handler();

    oc.OCMode       = TIM_OCMODE_PWM1;
    oc.Pulse        = SERVO_CENTER_US;
    oc.OCPolarity   = TIM_OCPOLARITY_HIGH;
    oc.OCFastMode   = TIM_OCFAST_DISABLE;
    oc.OCIdleState  = TIM_OCIDLESTATE_RESET;
    oc.OCNIdleState = TIM_OCNIDLESTATE_RESET;
    if (HAL_TIM_PWM_ConfigChannel(&htim1, &oc, TIM_CHANNEL_4) != HAL_OK) Error_Handler();

    bd.OffStateRunMode  = TIM_OSSR_DISABLE;
    bd.OffStateIDLEMode = TIM_OSSI_DISABLE;
    bd.LockLevel        = TIM_LOCKLEVEL_OFF;
    bd.DeadTime         = 0;
    bd.BreakState       = TIM_BREAK_DISABLE;
    bd.BreakPolarity    = TIM_BREAKPOLARITY_HIGH;
    bd.AutomaticOutput  = TIM_AUTOMATICOUTPUT_DISABLE;
    if (HAL_TIMEx_ConfigBreakDeadTime(&htim1, &bd) != HAL_OK) Error_Handler();

    HAL_TIM_MspPostInit(&htim1);
}

/* =====================================================================
   TIM3 — PWM for Motor 1 speed (CH1 → PA6/ENA, CH2 → PA7)
   72 MHz / (71+1) / (999+1) = 1 kHz PWM
   ===================================================================== */
static void MX_TIM3_Init(void)
{
    TIM_ClockConfigTypeDef  scc = {0};
    TIM_MasterConfigTypeDef mc  = {0};
    TIM_OC_InitTypeDef      oc  = {0};

    htim3.Instance               = TIM3;
    htim3.Init.Prescaler         = 71;
    htim3.Init.CounterMode       = TIM_COUNTERMODE_UP;
    htim3.Init.Period            = M1_PWM_PERIOD;
    htim3.Init.ClockDivision     = TIM_CLOCKDIVISION_DIV1;
    htim3.Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_DISABLE;
    if (HAL_TIM_Base_Init(&htim3) != HAL_OK) Error_Handler();

    scc.ClockSource = TIM_CLOCKSOURCE_INTERNAL;
    if (HAL_TIM_ConfigClockSource(&htim3, &scc) != HAL_OK) Error_Handler();
    if (HAL_TIM_PWM_Init(&htim3) != HAL_OK) Error_Handler();

    mc.MasterOutputTrigger = TIM_TRGO_RESET;
    mc.MasterSlaveMode     = TIM_MASTERSLAVEMODE_DISABLE;
    if (HAL_TIMEx_MasterConfigSynchronization(&htim3, &mc) != HAL_OK) Error_Handler();

    oc.OCMode     = TIM_OCMODE_PWM1;
    oc.Pulse      = 0;
    oc.OCPolarity = TIM_OCPOLARITY_HIGH;
    oc.OCFastMode = TIM_OCFAST_DISABLE;
    if (HAL_TIM_PWM_ConfigChannel(&htim3, &oc, TIM_CHANNEL_1) != HAL_OK) Error_Handler();
    if (HAL_TIM_PWM_ConfigChannel(&htim3, &oc, TIM_CHANNEL_2) != HAL_OK) Error_Handler();

    HAL_TIM_MspPostInit(&htim3);
}

/* =====================================================================
   USART2 — 115200, 8N1, printf retarget
   ===================================================================== */
static void MX_USART2_UART_Init(void)
{
    huart2.Instance          = USART2;
    huart2.Init.BaudRate     = 115200;
    huart2.Init.WordLength   = UART_WORDLENGTH_8B;
    huart2.Init.StopBits     = UART_STOPBITS_1;
    huart2.Init.Parity       = UART_PARITY_NONE;
    huart2.Init.Mode         = UART_MODE_TX_RX;
    huart2.Init.HwFlowCtl    = UART_HWCONTROL_NONE;
    huart2.Init.OverSampling = UART_OVERSAMPLING_16;
    if (HAL_UART_Init(&huart2) != HAL_OK) Error_Handler();
}

/* =====================================================================
   GPIO INIT
   ===================================================================== */
static void MX_GPIO_Init(void)
{
    GPIO_InitTypeDef g = {0};

    /* Pre-set outputs LOW before enabling clocks */
    __HAL_RCC_GPIOC_CLK_ENABLE();
    __HAL_RCC_GPIOD_CLK_ENABLE();
    __HAL_RCC_GPIOA_CLK_ENABLE();
    __HAL_RCC_GPIOB_CLK_ENABLE();

    /* ---- Output initial states ---- */
    HAL_GPIO_WritePin(GPIOC, GPIO_PIN_0|GPIO_PIN_1|GPIO_PIN_3|GPIO_PIN_5, GPIO_PIN_RESET);
    HAL_GPIO_WritePin(GPIOB, GPIO_PIN_0|GPIO_PIN_8|GPIO_PIN_9|GPIO_PIN_10|
                             GPIO_PIN_12|GPIO_PIN_13|GPIO_PIN_14|GPIO_PIN_15, GPIO_PIN_RESET);
    HAL_GPIO_WritePin(M1_ENA_PORT, M1_ENA_PIN, GPIO_PIN_RESET);
    HAL_GPIO_WritePin(M2_IN3_PORT, M2_IN3_PIN, GPIO_PIN_RESET);
    HAL_GPIO_WritePin(M2_IN4_PORT, M2_IN4_PIN, GPIO_PIN_RESET);

    /* ---- Blue button (PC13) — interrupt, no pull ---- */
    g.Pin  = B1_Pin;
    g.Mode = GPIO_MODE_IT_RISING;
    g.Pull = GPIO_NOPULL;
    HAL_GPIO_Init(B1_GPIO_Port, &g);

    /* ---- US TRIG outputs: PC0, PC1, PC3, PC5 ---- */
    g.Pin   = GPIO_PIN_0|GPIO_PIN_1|GPIO_PIN_3|GPIO_PIN_5;
    g.Mode  = GPIO_MODE_OUTPUT_PP;
    g.Pull  = GPIO_NOPULL;
    g.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(GPIOC, &g);

    /* ---- US ECHO inputs: PA4, PA5 (EXTI, pull-down) ---- */
    g.Pin  = GPIO_PIN_4|GPIO_PIN_5;
    g.Mode = GPIO_MODE_IT_RISING;
    g.Pull = GPIO_PULLDOWN;
    HAL_GPIO_Init(GPIOA, &g);

    /* ---- General PB outputs: trig PB0/PB10, buzzer PB8,
            LEDs PB9/PB12, motor ctrl PB13/PB14/PB15 ---- */
    g.Pin   = GPIO_PIN_0|GPIO_PIN_8|GPIO_PIN_9|GPIO_PIN_10|
              GPIO_PIN_12|GPIO_PIN_13|GPIO_PIN_14|GPIO_PIN_15;
    g.Mode  = GPIO_MODE_OUTPUT_PP;
    g.Pull  = GPIO_NOPULL;
    g.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(GPIOB, &g);

    /* ---- US ECHO inputs: PB1 (US5), PB11 (US6) — EXTI, pull-down ---- */
    g.Pin  = GPIO_PIN_1|GPIO_PIN_11;
    g.Mode = GPIO_MODE_IT_RISING;
    g.Pull = GPIO_PULLDOWN;
    HAL_GPIO_Init(GPIOB, &g);

    /* ---- US3 ECHO: PC6 — EXTI, pull-down ---- */
    g.Pin  = GPIO_PIN_6;
    g.Mode = GPIO_MODE_IT_RISING;
    g.Pull = GPIO_PULLDOWN;
    HAL_GPIO_Init(GPIOC, &g);

    /* ---- Motor 2 direction: PC7, PC8 — output ---- */
    g.Pin   = GPIO_PIN_7|GPIO_PIN_8;
    g.Mode  = GPIO_MODE_OUTPUT_PP;
    g.Pull  = GPIO_NOPULL;
    g.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(GPIOC, &g);
    HAL_GPIO_WritePin(GPIOC, GPIO_PIN_7|GPIO_PIN_8, GPIO_PIN_RESET);

    /* ---- USART2 TX (PA2) AF, RX (PA3) floating ---- */
    /* Handled by HAL_UART_MspInit */

    /* ---- EXTI priority ---- */
    HAL_NVIC_SetPriority(EXTI15_10_IRQn, 0, 0);
    HAL_NVIC_EnableIRQ(EXTI15_10_IRQn);
}

/* =====================================================================
   ERROR HANDLER
   ===================================================================== */
void Error_Handler(void)
{
    __disable_irq();
    while (1) {}
}

#ifdef USE_FULL_ASSERT
void assert_failed(uint8_t *file, uint32_t line)
{
    (void)file; (void)line;
}
#endif
